[package]
name = "alfred-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
zeromq = "0.3.5"
zmq2 = "0.5.0"
bytes = "1.6.0"
futures = "0.3.30"
toml = "0.8.13"
serde = "1.0.202"
serde_derive = "1.0.202"
envconfig = "0.10.0"
itertools = "0.13.0"
log = "0.4.21"
env_logger = "0.11.3" # only for daemon
