[package]
name = "alfred-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
zeromq = "0.3.5"
bytes = "1.6.0"
futures = "0.3.30"
